### ISSUE TITLE
NuGet dependency for .NET Framework?

### ISSUE THREAD

**Issue by danielrutten** [messagebird/csharp-rest-api#127]
The dependency in the NuGet package has changed from Any,Version=v0.0 to net6.0 so now we can no longer use it in our .NET Framework 4.7.2 project.

Is there a workaround for this, or even een different NuGet package we can use?

**Comment by vallerion** [comment]
Hi @danielrutten 
You can use [3.2 version](https://www.nuget.org/packages/MessageBird/3.2.0) of package.

**Comment by danielrutten** [comment]
I've got the 3.2 version but I'd like to have all my NuGet packages up to date. Is there going to be a .NET Framework version for 4.0.0, or is only .NET Core going to be supported?

**Comment by marcelcorso** [comment]
Hi @danielrutten! 
On the last version of the SDK we dropped support for .NET Framework 4.0.0 because it was old and it was making releasing complicated to us. 
I don't think it makes sense for us to support it in the future.

**Comment by danielrutten** [comment]
Thank you @marcelcorso! I've got a lot of big clients with big applications that are still on 4.7.2 and I don't see them switching to core anytime soon, but as long as 3.2 keeps working, I'm happy to stick with that.

**Comment by marcelcorso** [comment]
Let's try that then! Let us know if you run into new problems
