### ISSUE TITLE
Sending verification request not working

### ISSUE THREAD

**Issue by kevin-verpoort** [messagebird/csharp-rest-api#14]
Shouldn't orgininator be recipient?

File: csharp-rest-api/MessageBird/Objects/Verify.cs
Code: public Verify(string **originator**, VerifyOptionalArguments arguments = null) { ... }

**Comment by samwierema** [comment]
@kevin-verpoort thank you for opening the issue. We've identified the bug an will be implementing a patch and will release a new version.
