### ISSUE TITLE
Bug in validation of field Originator

### ISSUE THREAD

**Issue by vanwinssen** [messagebird/csharp-rest-api#17]
There is a bug in the validation of the field Originator.
When a value only exists of numeric characters (so being a phone number) then the value should not be validated on the length. This validation should only be applied on an alphanumeric value.

I noticed this bug because MessageBird sells Virtual Mobile Phone numbers, that can be 13 characters long (e.g: 3197001122334). The validation fails on this, and it shouldn't.

I made a proposal for a fix and added some tests. See PR #16 
Please verify. Thanks.

**Comment by samwierema** [comment]
Thanks again for opening the issue (and the pull request) @vanwinssen. We're publishing a new package to NuGet with version `1.3.2`.

**Comment by vanwinssen** [comment]
Great!
