### ISSUE TITLE
Allow value "auto" for DataEncoding

### ISSUE THREAD

**Issue by irgendwienet** [messagebird/csharp-rest-api#19]
The enum used in the library consists only of two values:
`public enum DataEncoding
    {
        [EnumMember(Value = "plain")]
        Plain,
        [EnumMember(Value = "unicode")]
        Unicode
};`

But in the API documentation at https://developers.messagebird.com/docs/messaging a 3rd value is descibed:
> The datacoding used, can be **plain** (GSM 03.38 characters only), **unicode** (contains non-GSM 03.38 characters) or **auto**, we will then set unicode or plain depending on the body content.

Can you add the value auto the this enum does a reason exist to not use "auto" from .net / C# side?

**Comment by samwierema** [comment]
@irgendwienet thanks for opening the issue. There's no reason it shouldn't be there. We'll get a patch out as soon as we can!

**Comment by samwierema** [comment]
This has now been released on NuGet as version 1.3.3.
