### ISSUE TITLE
NUGet package not compatible with Windows UWP

### ISSUE THREAD

**Issue by jsrijkee** [messagebird/csharp-rest-api#21]
It looks like the MessageBird NuGet is not compatible with the lates Windows UWP (see error messages)

Restoring packages for 'IAmOkShared'.
Restoring packages for D:\CloudStation\Visual Studio 2015\IAmOk\IAmOkShared\project.json...
MessageBird 1.3.2 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
MessageBird 1.3.2 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
MessageBird 1.3.2 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
MessageBird 1.3.2 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
MessageBird 1.3.2 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
MessageBird 1.3.2 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
MessageBird 1.3.2 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'IAmOkShared'.
Package restore failed. Rolling back package changes for 'IAmOkShared'.

Any idea when this is coming?

**Comment by samwierema** [comment]
Thanks for opening the issue @jsrijkee. There's no timeline yet for this, but the team we'll look into this soon.

**Comment by epels** [comment]
Hi @jsrijkee! This week we've released [version `1.3.7`](https://www.nuget.org/packages/MessageBird/1.3.7) of this package, which adds support for .NET Standard 2.0. According to [these docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), it should now be possible to use it in your UWP package. Make sure your project targets UWP version `>= 10.0.16299`.

I'm closing this issue as I'm assuming this resolves it. If it does not, or if you need any further assistance, please feel free to re-open! Thanks.
