### ISSUE TITLE
NuGet package not compatible with .NET Core

### ISSUE THREAD

**Issue by skhowaja** [messagebird/csharp-rest-api#23]
Package Manager Console Output:
--------------------------------------
Install-Package : Package MessageBird 1.3.4 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package MessageBird 1.3.4 supports: net (.NETFramework,Version=v0.0)
At line:1 char:1
+ Install-Package MessageBird
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:1
+ Install-Package MessageBird
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'IsmailiAlliances'.
At line:1 char:1
+ Install-Package MessageBird
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by wboevink** [comment]
Same with NETCORE2.0

Package 'MessageBird 1.3.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by samwierema** [comment]
@skhowaja thanks for opening an issue. We'll be looking at this next week.

**Comment by DeluxZ** [comment]
@samwierema @epels Check PR https://github.com/messagebird/csharp-rest-api/pull/40 please to support .NETStandard2.0 and .NETFramework4.0

**Comment by epels** [comment]
Hi @skhowaja, last week we've released [version `1.3.7`](https://www.nuget.org/packages/MessageBird/1.3.7) of this package, which adds support for .NET Standard 2.0. According to [these docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), it should now be possible to use it in your .NET Core package. Make sure your project targets .NET Core `>= 2.0`.

I'm closing this issue as I'm assuming this resolves it. If it does not, or if you need any further assistance, please feel free to re-open! Thanks.
