### ISSUE TITLE
NuGet Package may not be fully compatible with NETCORE2.0

### ISSUE THREAD

**Issue by wboevink** [messagebird/csharp-rest-api#26]
I got this warning when using the nuget package in a .net core v2.0 project

Package 'MessageBird 1.3.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

Eventually this will be a dealbreaker for us.

**Comment by facundofarias** [comment]
Any news on this!? :/

**Comment by samwierema** [comment]
@wboevink thanks for opening the issue. We'll be looking at this next week.

**Comment by DeluxZ** [comment]
@epels Check PR https://github.com/messagebird/csharp-rest-api/pull/40 please to support .NETStandard2.0 and .NETFramework4.0

**Comment by epels** [comment]
Hi @wboevink, last week we've released [version `1.3.7`](https://www.nuget.org/packages/MessageBird/1.3.7) of this package, which adds support for .NET Standard 2.0. According to [these docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), it should now be possible to use it in your .NET Core package. Make sure your project targets .NET Core `>= 2.0`.

I'm closing this issue as I'm assuming this resolves it. If it does not, or if you need any further assistance, please feel free to re-open! Thanks.

cc @facundofarias @ArneVanstechelman
