### ISSUE TITLE
Support request timeouts for outgoing requests

### ISSUE THREAD

**Issue by kwaazaar** [messagebird/csharp-rest-api#29]
See my PR: https://github.com/messagebird/csharp-rest-api/pull/28

**Comment by samwierema** [comment]
@kwaazaar thank for opening the issue. We'll be looking at your pull request next week.

**Comment by epels** [comment]
Hi @kwaazaar, thanks for submitting a pull request! Sorry it took us a little longer to get back to you. I'm closing this issue so we can continue the discussion in your PR.
