### ISSUE TITLE
Is anyone maintaining this project?

### ISSUE THREAD

**Issue by seanfarmar** [messagebird/csharp-rest-api#31]
I'd be happy to help

**Comment by samwierema** [comment]
@seanfarmar thanks for opening an issue. We are aware that there's some work on our C# client, and are trying to get some people involved internally. In the meantime, if you are willing, we'd be happy to receive new contributions or even thoughts on its current state. 

If you want to discuss privately, please feel free to reach out at sam@messagebird.com.

**Comment by epels** [comment]
Hi @seanfarmar, thanks for offering to help - it is much appreciated! As you may have noticed, we have released some improvements recently. I'm closing this issue for now. Please don't hesitate to reach out (privately or publicly) or open a new issue for specific questions, remarks or contributions! Thanks again for your initiative.
