### ISSUE TITLE
TokenLength Parameter Not Working in 2 Factor Authentication with number 

### ISSUE THREAD

**Issue by DaxeshVora** [messagebird/csharp-rest-api#57]
Hello Team,

We are implementing Message Bird API for implementing Two Factor Authentication in C# language. While doing that we were trying to use parameter tokenLength to set the size of token(OTP). But unfortunately its not sending code of given size instead every time it sends 6 Digit code only even though we have requested for 8 digit code.

We are using nuget package version 1.6.0

**Comment by marcelcorso** [comment]
hey @DaxeshVora I quickly checked the code and it should work. Note that here https://github.com/messagebird/csharp-rest-api/blob/19d33495c7faad8885ffa174137864c5aa5beb85/MessageBird/Objects/Verify.cs#L105 we declare the property and that's used to send the request to the server. 

Can you please try to be sure that this is a problem with this SDK? You can do that by just doing a curl request. 

if it's the API misbehaving then please let support know? You can contact them here https://support.messagebird.com/hc/en-us/

**Comment by DaxeshVora** [comment]
Yeah I have already tried with curl request directly and its working fine. And even got in touch with message bird team but they only redirected me here. So in conclusion can say it looks like some issue with SDK.

If you want any more info let me know.

**Comment by marcelcorso** [comment]
cool. Thanks. We will take a look.

**Comment by marcelcorso** [comment]
@DaxeshVora we  just merged a fix. 

https://github.com/messagebird/csharp-rest-api/commit/191c6dfcac5bcdb3d7b473bc94c742a53fb7b718

Thanks @Ali-BenZarrouk-MB.

**Comment by epels** [comment]
Hi @DaxeshVora, this PR was included in version `1.6.1`, which is now available on NuGet: https://www.nuget.org/packages/MessageBird/1.6.1

I assume this resolves the issue, so I'll close it: feel free to reopen it in case you run into any trouble upgrading.

Thanks!
