### ISSUE TITLE
VoiceMessageOptionalArguments is missing Originator

### ISSUE THREAD

**Issue by JWZondag** [messagebird/csharp-rest-api#6]

**Comment by samwierema** [comment]
Thank you for opening an issue. 

Could you tell me which version (or commit) of the client you are using?

**Comment by JWZondag** [comment]
Using the NuGet 1.0.5, but I also can't find it on GitHub in branch master.
I can find that originator was put in the VoiceMessage object.
According to the specs on the MessageBird website it is possible to provide the originator as an optional argument when sending a voice message.

**Comment by samwierema** [comment]
Yes, you're correct. We'll be pushing a fix for this tomorrow.

**Comment by samwierema** [comment]
Hey @JWZondag, we've added the necessary code to make it work. Will be pushing a new version to NuGet soon! 

Thank you for opening an issue! If you have any further issues, just let us know.

**Comment by JWZondag** [comment]
Thanks @samwierema ! 
*Do you have a timeframe for the NuGet push?*

**Comment by samwierema** [comment]
@JWZondag we expect to push this by tomorrow (sorry for the delay).

**Comment by samwierema** [comment]
@JWZondag a new package is now available from NuGet (v. 1.1.1).
