### ISSUE TITLE
Sending template message in whatsapp

### ISSUE THREAD

**Issue by Faheemmcfc** [messagebird/csharp-rest-api#83]
I am beginner with this api. How can we send templated message with whatsapp with this api. 
Can you please give me a sample code.

**Comment by ahmetkocadogan** [comment]
First, please read this https://developers.messagebird.com/docs/conversations/whatsapp/message-templates-curl/

There is a method named StartConversation, and expects ConversationStartRequest to send the message. 

For templated message, ConversationStartRequest.Content should be type of HsmContent.

**Comment by Faheemmcfc** [comment]
I have already gone through these, but didn't find anything related to C#. Please help... @ahmetkocadogan

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc  is your number verified ? Is there at least one template that is verified ?

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc  check this out.

https://github.com/ahmetkocadogan/MessageBirdWhatsAppTemplatedMessage

I tested this with WhatsApp sandbox, it works.

**Comment by Faheemmcfc** [comment]
My number is verified and have template verified. I will  check with your code and reply.. Thank you

**Comment by Faheemmcfc** [comment]
I was trying your code @ahmetkocadogan , but there is an error on line 

> Type=ContentType.Hsm

ContentType is not recognized. It shows 'An object reference is required for the non-static field,method of property'

What to do

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc since my example code works, i don't know what your issue is without seeing your code.

**Comment by Faheemmcfc** [comment]
I am using same code as your @ahmetkocadogan

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc I just checked my code, it works.

Your question is about a C# example of sending template message, i created that code for you. It is a console application. By just assigning the parameters (use sandbox, access key, to, channel id etc.) and HSM parameters, you can send template message.

The error you post  'An object reference is required for the non-static field,method of property' is not related with MessageBird C# SDK.

**Comment by Faheemmcfc** [comment]
I will try to work around it. Sorry for disturbing... @ahmetkocadogan

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc No need to be sorry, i am trying to help.

**Comment by Faheemmcfc** [comment]
Yeah. I know. Thank you. Will need more help. I will contact you..

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc  any luck ?

**Comment by Faheemmcfc** [comment]
sorry @ahmetkocadogan, was busy with some other works... I tried it, but some errors are there. It's showing some error related to api server address.. Error : 'The remote name could not be resolved: 'whatsapp-sandbox.messagebird.com'.
 
Can you please check that? It will be a great help...
Thank you

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc my example code has a parameter

const bool _useWhatsAppSandbox = true

If you are using whatsapp sandbox, this parameter should be true, otherwise assign it as false.

**Comment by Faheemmcfc** [comment]
`const bool _useWhatsAppSandbox = false;
        const string YourAccessKey = "####"; // your access key here.
        const string ChannelId = "####"; // your channel id here
        const string To = "####"; // receiver phone number here
        const string HsmNamespace = "872b6ac6_d271_4995_b0f8_3d8b8b5451a4"; // HSM namespace here
        const string TemplateName = "newupdation"; // template name here
        const string HsmLanguageCode = "en"; // HSM language code
        Client _client;
        ServicePointManager.Expect100Continue = true;
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

        if (_useWhatsAppSandbox)
        {
            _client = Client.CreateDefault(YourAccessKey, features: new Client.Features[] { Client.Features.EnableWhatsAppSandboxConversations });
        }
        else
        {
            _client = Client.CreateDefault(YourAccessKey);
        }

        try
        {
            Conversation conversation = _client.StartConversation(new ConversationStartRequest()
            {
                ChannelId = ChannelId,
                To = To,
                //Type = ContentType.Hsm,
                Content = new MessageBird.Objects.Conversations.Content()
                {
                    Hsm = new HsmContent()
                    {
                        Namespace = HsmNamespace,
                        TemplateName = TemplateName,
                        Language = new HsmLanguage()
                        {
                            Code = HsmLanguageCode,
                            Policy = HsmLanguagePolicy.Deterministic
                        },
                        Params = new System.Collections.Generic.List<HsmLocalizableParameter>()
                        {
                            new HsmLocalizableParameter(){Default = "Faheem"},
                            new HsmLocalizableParameter(){Default = "ABCD"},
                            //new HsmLocalizableParameter(){Default = "new coffee machine"},
                            //new HsmLocalizableParameter(){Default = "MessageBird, Trompenburgstraat 2C, 1079TX Amsterdam"},
                        }
                    }
                }
            });
            Console.WriteLine("{0}", conversation);
        }
        catch (ErrorException e)
        {
            // Either the request fails with error descriptions from the endpoint.
            if (e.HasErrors)
            {
                foreach (Error error in e.Errors)
                {
                    Console.WriteLine("code: {0} description: '{1}' parameter: '{2}'", error.Code, error.Description, error.Parameter);
                }
            }
            // or fails without error information from the endpoint, in which case the reason contains a 'best effort' description.
            if (e.HasReason)
            {
                Console.WriteLine(e.Reason);
            }
        }
        Console.WriteLine("Press any key to continue...");
        Console.ReadKey();
`

This is the current code  I am using. Current error is: the remote server returned an error 400 bad request..

I am not at all familiar with these problems. 

Thanks in advance... @ahmetkocadogan

**Comment by Faheemmcfc** [comment]
Can you help me with this @ahmetkocadogan 
What is `Type = ContentType.Hsm,`?
It's showing there is no definition for Hsm. I don't see any definition either in your code. Is there anything else to do?

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc 
This is the documentation for WhatsApp Message Templates
https://developers.messagebird.com/docs/conversations/whatsapp/message-templates-curl/

HSM stands for Highly Structured Message. This is the content type that you should use to send templated messages.

**Comment by Faheemmcfc** [comment]
But I cannot see the definition for ContentType.Hsm in your code. @ahmetkocadogan

**Comment by Faheemmcfc** [comment]
Sorry to bother you @ahmetkocadogan. I am using exact same code of you except it's a templated message. But Type=ContentType.Hsm is giving error. I have attached the screenshot, please look through it...
![Screenshot (43)](https://user-images.githubusercontent.com/26008840/97185348-f026c180-17c5-11eb-8067-61a9a5dffe65.png)

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc 
Did you include `using MessageBird.Objects.Conversations;` ?

**Comment by Faheemmcfc** [comment]
Yes.. Here is the full code:

`using ERPFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using MessageBird;
using MessageBird.Exceptions;
using MessageBird.Objects;
using MessageBird.Objects.Conversations;
using System.Net;
using System.Collections.Specialized;
using MessageBird.Net.ProxyConfigurationInjector;

public partial class Default3 : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        Session["LoginStatus"] = "False";
        //Balance();
        SendMessage();
    }    

    void SendMessage()
    {
        const bool _useWhatsAppSandbox = false;
        const string YourAccessKey = "zSJ7BdNFlrmCqy1######"; // your access key here.
        const string ChannelId = "77cbee46da1e4bf3931b91####"; // your channel id here
        const string To = "+919037181603"; // receiver phone number here
        const string HsmNamespace = "872b6ac6_d271_4995_b0f8_3d8b8b####"; // HSM namespace here
        const string TemplateName = "newupdation"; // template name here
        const string HsmLanguageCode = "en"; // HSM language code
        Client _client;
        ServicePointManager.Expect100Continue = true;
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

        if (_useWhatsAppSandbox)
        {
            _client = Client.CreateDefault(YourAccessKey, features: new Client.Features[] { Client.Features.EnableWhatsAppSandboxConversations });
        }
        else
        {
            _client = Client.CreateDefault(YourAccessKey);
        }

        try
        {
            Conversation conversation = _client.StartConversation(new ConversationStartRequest()
            {
                ChannelId = ChannelId,
                To = To,
                Type =ContentType.Hsm,
                Content = new MessageBird.Objects.Conversations.Content()
                {
                    Hsm = new HsmContent()
                    {
                        Namespace = HsmNamespace,
                        TemplateName = TemplateName,
                        Language = new HsmLanguage()
                        {
                            Code = HsmLanguageCode,
                            Policy = HsmLanguagePolicy.Deterministic
                        },
                        Params = new System.Collections.Generic.List<HsmLocalizableParameter>()
                        {
                            new HsmLocalizableParameter(){Default = "Faheem"},
                            new HsmLocalizableParameter(){Default = "ABCD"},
                            //new HsmLocalizableParameter(){Default = "new coffee machine"},
                            //new HsmLocalizableParameter(){Default = "MessageBird, Trompenburgstraat 2C, 1079TX Amsterdam"},
                        }
                    }
                }
            });
            Console.WriteLine("{0}", conversation);
        }
        catch (ErrorException e)
        {
            // Either the request fails with error descriptions from the endpoint.
            if (e.HasErrors)
            {
                foreach (Error error in e.Errors)
                {
                    Console.WriteLine("code: {0} description: '{1}' parameter: '{2}'", error.Code, error.Description, error.Parameter);
                }
            }
            // or fails without error information from the endpoint, in which case the reason contains a 'best effort' description.
            if (e.HasReason)
            {
                Console.WriteLine(e.Reason);
            }
        }
        Console.WriteLine("Press any key to continue...");
        Console.ReadKey();

    }`

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc 
Maybe you added System.Net.Mime instead of MessageBird.Objects.Conversations
![image](https://user-images.githubusercontent.com/7287309/97190815-44767500-17b7-11eb-917d-f74fbecbec9b.png)

**Comment by Faheemmcfc** [comment]
No.. Added it correctly. Please check above comment

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc 

When you hover over ContentType, do you see this ?

![image](https://user-images.githubusercontent.com/7287309/97191287-c8c8f800-17b7-11eb-80f6-1595d2f2784f.png)

**Comment by Faheemmcfc** [comment]
No... 
![Screenshot (44)](https://user-images.githubusercontent.com/26008840/97191494-f2d8e500-17cc-11eb-867c-52c359b800dd.png)

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc 
change `ContentType.Hsm` to `MessageBird.Objects.Conversations.ContentType.Hsm`

**Comment by Faheemmcfc** [comment]
Oh man!!.. Thanks a lot.. It finally worked... It was a great help @ahmetkocadogan

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc 
Screen shot is your savior :) I did not understand the issue until the screen shot :)

glad to help.

**Comment by ahmetkocadogan** [comment]
@Faheemmcfc you can close the issue, if it is resolved for you.

**Comment by Faheemmcfc** [comment]
okay.. sure... Thanks
