### ISSUE TITLE
Add support for email verify 

### ISSUE THREAD

**Issue by iuliia-filatova** [messagebird/csharp-rest-api#96]
https://developers.messagebird.com/api/verifywithemail/#request-a-verify
recipient and originator for now could be set as an email (now string previously were int)

Add support to get status of the verify email message 
`verify/messages/email`

**Comment by sandipdavari** [comment]
I am not able to see any update on verify by Email in code.
Please share the code link or updated dll with message type Email, if you have.

**Comment by ldominique92** [comment]
@sandipdavari we have released an update in Nuget enabling email, did you see it?
